<?php

declare(strict_types=1);

namespace App\Commands\Cloning;

use App\Data\ConnectionData;
use App\Data\Schema\ColumnSchemaData;
use App\Data\Schema\DatabaseSchemaData;
use App\Data\Schema\TableSchemaData;
use App\Enums\ExitCode;
use App\Enums\KeyRemappingStrategy;
use App\Services\Config\ConfigService;
use App\Services\Database\DatabaseConnectionService;
use App\Services\Schema\SchemaInspector;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use LaravelZero\Framework\Commands\Command;
use Symfony\Component\Yaml\Yaml;
use Throwable;

class ColumnEditCommand extends Command
{
    /**
     * @var string
     */
    protected $signature = 'cloning:column:edit
        {file?              : Path to the .cloning.yaml file}
        {--table=           : Table name}
        {--column=          : Column name}
        {--strategy=        : Strategy to apply (keep, fake, hash, mask, static, remapping)}
        {--faker-method=    : (fake) Faker method name}
        {--faker-arguments= : (fake) Comma-separated faker arguments}
        {--algorithm=       : (hash) Hash algorithm}
        {--salt=            : (hash) Hash salt}
        {--mask-char=       : (mask) Mask character}
        {--visible-chars=   : (mask) Number of visible characters}
        {--preserve-format  : (mask) Preserve original format}
        {--value=           : (static) Static replacement value}
        {--remapping-use=   : (remapping) random_integer | new_uuid}';

    /**
     * @var string
     */
    protected $description = 'Edit a column strategy in a cloning configuration YAML file';

    /**
     * Strategy definitions with labels and parameter descriptions.
     *
     * @return array<string, array{label: string, description: string, parameters: list<array{name: string, label: string, type: string, default: string}>}>
     */
    private function strategyDefinitions(): array
    {
        return [
            'keep' => [
                'label' => 'Keep',
                'description' => 'Copy the original value as-is — no transformation applied.',
                'parameters' => [],
            ],
            'fake' => [
                'label' => 'Fake',
                'description' => 'Replace with a realistic fake value generated by FakerPHP.',
                'parameters' => [
                    ['name' => 'faker_method', 'label' => 'Faker method', 'type' => 'choice', 'default' => 'safeEmail'],
                    ['name' => 'faker_arguments', 'label' => 'Faker arguments (comma-separated)', 'type' => 'string', 'default' => ''],
                ],
            ],
            'hash' => [
                'label' => 'Hash',
                'description' => 'Replace with a one-way hash of the original value. Useful for passwords and secrets.',
                'parameters' => [
                    ['name' => 'algorithm', 'label' => 'Algorithm', 'type' => 'choice', 'default' => 'sha256'],
                    ['name' => 'salt', 'label' => 'Salt (optional)', 'type' => 'string', 'default' => ''],
                ],
            ],
            'mask' => [
                'label' => 'Mask',
                'description' => 'Partially mask the value, preserving a configurable number of visible characters.',
                'parameters' => [
                    ['name' => 'visible_chars', 'label' => 'Visible characters', 'type' => 'integer', 'default' => '0'],
                    ['name' => 'mask_char', 'label' => 'Mask character', 'type' => 'string', 'default' => '*'],
                    ['name' => 'preserve_format', 'label' => 'Preserve format', 'type' => 'confirm', 'default' => 'false'],
                ],
            ],
            'static' => [
                'label' => 'Static',
                'description' => 'Replace every value with a fixed string.',
                'parameters' => [
                    ['name' => 'value', 'label' => 'Static value', 'type' => 'string', 'default' => ''],
                ],
            ],
            'remapping' => [
                'label' => 'Remapping',
                'description' => 'Replace primary key values; foreign keys auto-detected from the source schema.',
                'parameters' => [
                    ['name' => 'remapping_use', 'label' => 'Remapping mode', 'type' => 'choice', 'default' => 'random_integer'],
                ],
            ],
        ];
    }

    /** @var array<string, string> */
    private const array REMAPPING_USE_LABELS = [
        'random_integer' => 'Random integer — auto-bounded by column type ceiling',
        'new_uuid' => 'New UUID (UUIDv7)',
    ];

    /** @var list<string> */
    private const array FAKER_METHODS = [
        'safeEmail', 'userName', 'name', 'firstName', 'lastName',
        'phoneNumber', 'address', 'city', 'postcode', 'countryCode',
        'company', 'jobTitle', 'date', 'latitude', 'longitude',
        'buildingNumber', 'text', 'sentence', 'url', 'ipv4',
        'uuid', 'word', 'numberBetween', 'randomFloat',
    ];

    /**
     * Arguments each faker method accepts, as human-readable hints.
     * Methods with an empty list take no arguments.
     *
     * @var array<string, list<string>>
     */
    private const array FAKER_METHOD_ARGS = [
        'safeEmail' => [],
        'userName' => [],
        'name' => [],
        'firstName' => [],
        'lastName' => [],
        'phoneNumber' => [],
        'address' => [],
        'city' => [],
        'postcode' => [],
        'countryCode' => [],
        'company' => [],
        'jobTitle' => [],
        'date' => ['format (string, e.g. "Y-m-d")', 'max (string|null, e.g. "now")'],
        'latitude' => ['min (float, default -90)', 'max (float, default 90)'],
        'longitude' => ['min (float, default -180)', 'max (float, default 180)'],
        'buildingNumber' => [],
        'text' => ['maxNbChars (int, default 200)'],
        'sentence' => ['nbWords (int, default 6)', 'variableNbWords (bool, default true)'],
        'url' => [],
        'ipv4' => [],
        'uuid' => [],
        'word' => [],
        'numberBetween' => ['min (int, default 0)', 'max (int, default 2147483647)'],
        'randomFloat' => ['nbMaxDecimals (int|null)', 'min (float, default 0)', 'max (float, default 100)'],
    ];

    /** @var list<string> */
    private const array HASH_ALGORITHMS = ['sha256', 'sha512', 'md5', 'sha1'];

    public function handle(
        ConfigService $configService,
        DatabaseConnectionService $connector,
        SchemaInspector $inspector,
    ): int {
        // ─── Resolve file ──────────────────────────────────────────────────
        $fileArg = $this->argument('file');
        $filePath = is_string($fileArg) && $fileArg !== '' ? $fileArg : null;

        if ($filePath === null) {
            // Find .cloning.yaml files in cwd
            $allFiles = Storage::disk('local')->files('.');
            $files = array_values(array_filter(
                $allFiles,
                static fn (mixed $f): bool => is_string($f) && str_ends_with($f, '.cloning.yaml'),
            ));

            if ($files === []) {
                $this->error('No .cloning.yaml files found in the current directory.');

                return ExitCode::IoError->value;
            }

            if (count($files) === 1) {
                $filePath = $files[0];
            } else {
                $chosen = $this->choice('Select a cloning YAML file', $files, 0);
                $filePath = is_string($chosen) ? $chosen : $files[0];
            }
        }

        /** @var string $filePath */
        if (! Storage::disk('local')->exists($filePath)) {
            $this->error(sprintf('File not found: %s', $filePath));

            return ExitCode::IoError->value;
        }

        $content = Storage::disk('local')->get($filePath);

        if (! is_string($content)) {
            $this->error(sprintf('Cannot read file: %s', $filePath));

            return ExitCode::IoError->value;
        }

        $data = Yaml::parse($content);

        if (! is_array($data) || ! is_array($data['tables'] ?? null)) {
            $this->error('Invalid cloning YAML: missing tables section.');

            return ExitCode::ValidationError->value;
        }

        /** @var array<string, mixed> $data */
        /** @var array<string, mixed> $tables */
        $tables = $data['tables'];

        // ─── Resolve table ─────────────────────────────────────────────────
        $tableOption = $this->option('table');
        $tableName = is_string($tableOption) && $tableOption !== '' ? $tableOption : null;

        if ($tableName === null) {
            $tableNames = array_keys($tables);
            $chosen = $this->choice('Select a table', $tableNames, 0);
            $tableName = is_string($chosen) ? $chosen : $tableNames[0];
        }

        if (! isset($tables[$tableName])) {
            $this->error(sprintf("Table '%s' not found in the YAML file.", $tableName));

            return ExitCode::ValidationError->value;
        }

        /** @var array<string, mixed> $tableConfig */
        $tableConfig = $tables[$tableName];

        /** @var array<string, mixed> $columns */
        $columns = is_array($tableConfig['columns'] ?? null) ? $tableConfig['columns'] : [];

        // ─── Resolve column ────────────────────────────────────────────────
        $columnOption = $this->option('column');
        $columnName = is_string($columnOption) && $columnOption !== '' ? $columnOption : null;

        if ($columnName === null) {
            if ($columns === []) {
                $asked = $this->ask('Column name (no columns listed yet — enter the name to add)');
                $columnName = is_string($asked) ? $asked : '';
            } else {
                $colNames = array_keys($columns);
                $colNames[] = '+ Add new column';
                $chosen = $this->choice('Select a column', $colNames, 0);

                if ($chosen === '+ Add new column') {
                    $asked = $this->ask('Column name');
                    $columnName = is_string($asked) ? $asked : '';
                } else {
                    $columnName = is_string($chosen) ? $chosen : $colNames[0];
                }
            }
        }

        if ($columnName === '') {
            $this->error('Column name cannot be empty.');

            return ExitCode::ValidationError->value;
        }

        // Show current config if the column exists
        $currentConfig = $columns[$columnName] ?? null;

        if (is_array($currentConfig)) {
            $currentStrategy = is_string($currentConfig['strategy'] ?? null) ? $currentConfig['strategy'] : 'keep';
            $this->line(sprintf('  Current strategy for <info>%s.%s</info>: <comment>%s</comment>', $tableName, $columnName, $currentStrategy));
            $this->line('');
        }

        // ─── Resolve strategy ──────────────────────────────────────────────
        $definitions = $this->strategyDefinitions();
        $strategyOption = $this->option('strategy');
        $strategyKey = is_string($strategyOption) && $strategyOption !== '' ? $strategyOption : null;

        if ($strategyKey === null) {
            // Build choice list with descriptions
            $labels = [];

            foreach ($definitions as $key => $def) {
                $labels[$key] = sprintf('%s — %s', $def['label'], $def['description']);
            }

            $chosen = $this->choice('Select a strategy', array_values($labels), 0);
            $strategyKey = is_string($chosen)
                ? array_search($chosen, $labels, true)
                : 'keep';

            if (! is_string($strategyKey)) {
                $strategyKey = 'keep';
            }
        }

        if (! isset($definitions[$strategyKey])) {
            $this->error(sprintf("Unknown strategy: '%s'. Valid: %s", $strategyKey, implode(', ', array_keys($definitions))));

            return ExitCode::ValidationError->value;
        }

        $definition = $definitions[$strategyKey];

        // Validate --remapping-use flag value upfront (if provided).
        $useFlag = $this->option('remapping-use');
        if ($strategyKey === 'remapping' && is_string($useFlag) && $useFlag !== '' && ! in_array($useFlag, KeyRemappingStrategy::values(), true)) {
            $this->error(sprintf("Unknown remapping use: '%s'. Valid: %s", $useFlag, implode(', ', KeyRemappingStrategy::values())));

            return ExitCode::ValidationError->value;
        }

        // ─── Collect parameters ────────────────────────────────────────────
        /** @var array<string, mixed> $newConfig */
        $newConfig = ['strategy' => $strategyKey];

        foreach ($definition['parameters'] as $param) {
            // Skip faker_arguments when the chosen faker method takes no arguments
            if ($param['name'] === 'faker_arguments') {
                $chosenMethod = is_string($newConfig['faker_method'] ?? null) ? $newConfig['faker_method'] : '';
                $argHints = self::FAKER_METHOD_ARGS[$chosenMethod] ?? null;

                if ($argHints === []) {
                    // No arguments for this method — store empty array and skip prompt
                    $newConfig[$param['name']] = [];

                    continue;
                }
            }

            $value = $this->collectParameter($param);
            if ($value !== null) {
                $newConfig[$param['name']] = $value;
            }
        }

        // ─── Remapping: resolve source schema, validate PK, detect FKs ─────
        /** @var list<array{table: string, column: string, self_referential: bool}> $remappingForeignKeys */
        $remappingForeignKeys = [];

        if ($strategyKey === 'remapping') {
            $connectionName = is_string($data['connection'] ?? null) ? $data['connection'] : '';
            $remappingContext = $this->resolveRemappingContext(
                connectionName: $connectionName,
                tableName: $tableName,
                columnName: $columnName,
                configService: $configService,
                connector: $connector,
                inspector: $inspector,
            );

            if ($remappingContext['error'] !== null) {
                $this->error($remappingContext['error']);

                return ExitCode::ValidationError->value;
            }

            $remappingForeignKeys = $remappingContext['foreignKeys'];
        }

        // ─── Summary ──────────────────────────────────────────────────────
        $this->line('');
        $rows = [['Table', $tableName], ['Column', $columnName], ['Strategy', $definition['label']]];

        foreach ($definition['parameters'] as $param) {
            $paramValue = $newConfig[$param['name']] ?? null;
            if ($paramValue !== null) {
                $display = is_array($paramValue)
                    ? implode(', ', array_map(static fn (mixed $v): string => is_scalar($v) ? (string) $v : '', $paramValue))
                    : (is_bool($paramValue) ? ($paramValue ? 'true' : 'false') : (is_scalar($paramValue) ? (string) $paramValue : ''));
                $rows[] = [$param['label'], $display];
            }
        }

        if ($strategyKey === 'remapping') {
            $rows[] = ['Foreign keys (auto-detected)', $remappingForeignKeys === []
                ? '— none —'
                : implode(', ', array_map(
                    static fn (array $fk): string => sprintf(
                        '%s.%s%s',
                        $fk['table'],
                        $fk['column'],
                        $fk['self_referential'] ? ' (self)' : '',
                    ),
                    $remappingForeignKeys,
                ))];
        }

        /** @var string $strategyKey */
        $this->table(['Field', 'Value'], $rows);

        if (! $this->confirm('Apply this change?', true)) {
            $this->line('Cancelled.');

            return ExitCode::Success->value;
        }

        // ─── Apply ─────────────────────────────────────────────────────────
        // Normalise faker_arguments from comma-separated string to list
        if (isset($newConfig['faker_arguments']) && is_string($newConfig['faker_arguments'])) {
            $raw = $newConfig['faker_arguments'];
            $newConfig['faker_arguments'] = $raw !== ''
                ? array_map(static function (string $v): int|float|string {
                    $v = trim($v);
                    if (is_numeric($v)) {
                        return str_contains($v, '.') ? (float) $v : (int) $v;
                    }

                    return $v;
                }, explode(',', $raw))
                : [];
        }

        // Convert preserve_format to bool
        if (isset($newConfig['preserve_format'])) {
            $newConfig['preserve_format'] = (bool) $newConfig['preserve_format'];
        }

        // Convert visible_chars to int
        if (isset($newConfig['visible_chars'])) {
            $visibleCharsVal = $newConfig['visible_chars'];
            $newConfig['visible_chars'] = is_numeric($visibleCharsVal) ? (int) $visibleCharsVal : 0;
        }

        // Reshape remapping config into arguments-list form (mirrors cloning:dump output)
        if ($strategyKey === 'remapping') {
            $use = is_string($newConfig['remapping_use'] ?? null) ? $newConfig['remapping_use'] : 'random_integer';
            $newConfig = [
                'strategy' => 'remapping',
                'arguments' => [
                    ['use' => $use],
                    ['foreign_keys' => $remappingForeignKeys],
                ],
            ];
        }

        $columns[$columnName] = $newConfig;
        $tableConfig['columns'] = $columns;
        /** @var array<string, mixed> $dataTables */
        $dataTables = $data['tables'];
        $dataTables[$tableName] = $tableConfig;
        $data['tables'] = $dataTables;

        $yaml = Yaml::dump($data, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK | Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
        Storage::disk('local')->put($filePath, $yaml);

        $this->info(sprintf('Updated %s.%s → strategy: %s in %s', $tableName, $columnName, $strategyKey, $filePath));

        return ExitCode::Success->value;
    }

    /**
     * @param  array{name: string, label: string, type: string, default: string}  $param
     */
    private function collectParameter(array $param): mixed
    {
        // Check if a CLI option was provided
        $optionName = str_replace('_', '-', $param['name']);
        $opt = $this->option($optionName);

        if ($opt === true && $param['type'] === 'confirm') {
            return true;
        }

        if (is_string($opt)) {
            // When faker_method is supplied via flag, still show the argument hint
            if ($param['name'] === 'faker_method') {
                $this->showFakerMethodHint($opt);
            }

            return $opt;
        }

        return match ($param['type']) {
            'choice' => $this->collectChoiceParameter($param),
            'confirm' => $this->confirm($param['label'], $param['default'] === 'true'),
            'integer' => (int) $this->askString($param['label'], $param['default']),
            default => $this->askStringOrNull($param['label'], $param['default']),
        };
    }

    private function showFakerMethodHint(string $method): void
    {
        $argHints = self::FAKER_METHOD_ARGS[$method] ?? null;

        if ($argHints === []) {
            $this->line(sprintf('  <comment>ℹ</comment>  %s() takes no arguments — leave faker arguments blank.', $method));
        } elseif ($argHints !== null) {
            $this->line(sprintf('  <comment>ℹ</comment>  %s() arguments: %s', $method, implode(', ', $argHints)));
        }
    }

    /**
     * @param  array{name: string, label: string, type: string, default: string}  $param
     */
    private function collectChoiceParameter(array $param): string
    {
        if ($param['name'] === 'faker_method') {
            $methods = self::FAKER_METHODS;
            $defaultIdx = (int) array_search($param['default'], $methods, true);
            $chosen = $this->choice($param['label'], $methods, $defaultIdx);
            $method = is_string($chosen) ? $chosen : $param['default'];

            $this->showFakerMethodHint($method);

            return $method;
        }

        if ($param['name'] === 'algorithm') {
            $algos = self::HASH_ALGORITHMS;
            $defaultIdx = (int) array_search($param['default'], $algos, true);
            $chosen = $this->choice($param['label'], $algos, $defaultIdx);

            return is_string($chosen) ? $chosen : $param['default'];
        }

        if ($param['name'] === 'remapping_use') {
            $useValues = array_keys(self::REMAPPING_USE_LABELS);
            $useLabels = array_values(self::REMAPPING_USE_LABELS);
            $defaultIdx = (int) array_search($param['default'], $useValues, true);
            $chosen = $this->choice($param['label'], $useLabels, $defaultIdx);
            $key = is_string($chosen) ? array_search($chosen, self::REMAPPING_USE_LABELS, true) : false;

            return is_string($key) ? $key : $param['default'];
        }

        return $param['default'];
    }

    /**
     * Resolve source schema for a remapping column: validate the column is a primary key and
     * auto-detect reverse foreign keys (other tables whose FKs reference this PK).
     *
     * @return array{error: ?string, foreignKeys: list<array{table: string, column: string, self_referential: bool}>}
     */
    private function resolveRemappingContext(
        string $connectionName,
        string $tableName,
        string $columnName,
        ConfigService $configService,
        DatabaseConnectionService $connector,
        SchemaInspector $inspector,
    ): array {
        if ($connectionName === '') {
            $this->warn('  Source connection unknown (YAML missing top-level "connection") — writing foreign_keys: [] and skipping primary-key validation.');

            return ['error' => null, 'foreignKeys' => []];
        }

        $connection = $configService->getConnection($connectionName);

        if (! $connection instanceof ConnectionData) {
            $this->warn(sprintf("  Source connection '%s' not found in clonio.json — writing foreign_keys: [] and skipping primary-key validation.", $connectionName));

            return ['error' => null, 'foreignKeys' => []];
        }

        try {
            $connName = $connector->open($connection);

            try {
                $schema = $inspector->inspect($connection);
            } finally {
                DB::purge($connName);
            }
        } catch (Throwable $throwable) {
            $this->warn(sprintf('  Source connection unreachable (%s) — writing foreign_keys: [] and skipping primary-key validation.', $throwable->getMessage()));

            return ['error' => null, 'foreignKeys' => []];
        }

        $table = $schema->getTable($tableName);

        if (! $table instanceof TableSchemaData) {
            return [
                'error' => sprintf("Table '%s' does not exist in source schema for connection '%s'.", $tableName, $connectionName),
                'foreignKeys' => [],
            ];
        }

        $column = array_find($table->columns, static fn (ColumnSchemaData $col): bool => $col->name === $columnName);

        if (! $column instanceof ColumnSchemaData) {
            return [
                'error' => sprintf("Column '%s' does not exist on table '%s' in source schema.", $columnName, $tableName),
                'foreignKeys' => [],
            ];
        }

        if (! $column->isPrimary) {
            return [
                'error' => sprintf("Column '%s.%s' is not a primary key in source schema — remapping requires a primary-key column.", $tableName, $columnName),
                'foreignKeys' => [],
            ];
        }

        return ['error' => null, 'foreignKeys' => $this->detectReverseForeignKeys($schema, $tableName, $columnName)];
    }

    /**
     * Scan every table for FK columns referencing <tableName>.<columnName>.
     *
     * @return list<array{table: string, column: string, self_referential: bool}>
     */
    private function detectReverseForeignKeys(DatabaseSchemaData $schema, string $tableName, string $columnName): array
    {
        $foreignKeys = [];

        foreach ($schema->tables as $sourceTable) {
            foreach ($sourceTable->foreignKeys as $fk) {
                if ($fk->referencedTable !== $tableName) {
                    continue;
                }

                if ($fk->referencedColumn !== $columnName) {
                    continue;
                }

                $foreignKeys[] = [
                    'table' => $sourceTable->name,
                    'column' => $fk->columnName,
                    'self_referential' => $sourceTable->name === $tableName,
                ];
            }
        }

        return $foreignKeys;
    }

    private function askString(string $question, string $default): string
    {
        $answer = $this->ask($question, $default !== '' ? $default : null);

        return is_string($answer) ? $answer : $default;
    }

    private function askStringOrNull(string $question, string $default): ?string
    {
        $answer = $this->ask($question, $default !== '' ? $default : null);
        $value = is_string($answer) ? $answer : $default;

        return $value !== '' ? $value : null;
    }
}
