<?php

declare(strict_types=1);

namespace App\Services\SqlDump\Dialects;

use App\Data\Schema\ColumnSchemaData;
use App\Data\Schema\TableSchemaData;
use App\Services\SqlDump\Contracts\SqlDumpDialect;
use DateTimeImmutable;

/**
 * Shared rendering logic for SQL dump dialects.
 *
 * Note on fidelity (v1): the schema layer (ColumnSchemaData) exposes only the
 * base data type (e.g. `varchar`, `decimal`) without length/precision, so DDL
 * uses conservative default lengths (VARCHAR(255), DECIMAL(20,6)). Primary keys
 * are emitted as plain columns — no AUTO_INCREMENT/SERIAL/IDENTITY — because the
 * pipeline always inserts explicit key values. DEFAULT clauses are omitted for
 * the same reason (every column value is copied explicitly).
 */
abstract class AbstractDumpDialect implements SqlDumpDialect
{
    protected const int DEFAULT_VARCHAR_LENGTH = 255;

    abstract protected function dialectDisplayName(): string;

    abstract public function quoteIdentifier(string $name): string;

    /** Table reference as used inside statements (SQL Server prefixes the schema). */
    abstract protected function qualifiedTable(string $table): string;

    /** Map a source column to this dialect's column type for DDL. */
    abstract protected function mapColumnType(ColumnSchemaData $column): string;

    /** Binary literal for a hex-encoded value (without the leading `0x`/`X'` differences). */
    abstract protected function binaryLiteral(string $hex): string;

    public function fileHeader(string $sourceDb, DateTimeImmutable $at): string
    {
        return sprintf(
            "-- Dump generated by Clonio for %s\n-- Source: %s | Date: %s\n\n",
            $this->dialectDisplayName(),
            $sourceDb,
            $at->format('Y-m-d H:i:s'),
        );
    }

    public function dropTable(string $table): string
    {
        return sprintf('DROP TABLE IF EXISTS %s;', $this->qualifiedTable($table))."\n";
    }

    public function createTable(TableSchemaData $table, bool $ifNotExists): string
    {
        $lines = [];

        foreach ($table->columns as $column) {
            $lines[] = sprintf(
                '  %s %s%s',
                $this->quoteIdentifier($column->name),
                $this->mapColumnType($column),
                $column->nullable ? '' : ' NOT NULL',
            );
        }

        $pk = array_values(array_filter(
            $table->columns,
            static fn (ColumnSchemaData $c): bool => $c->isPrimary,
        ));

        if ($pk !== []) {
            $pkCols = implode(', ', array_map(
                fn (ColumnSchemaData $c): string => $this->quoteIdentifier($c->name),
                $pk,
            ));
            $lines[] = sprintf('  PRIMARY KEY (%s)', $pkCols);
        }

        $keyword = $ifNotExists ? 'CREATE TABLE IF NOT EXISTS' : 'CREATE TABLE';

        return sprintf("%s %s (\n%s\n);\n", $keyword, $this->qualifiedTable($table->name), implode(",\n", $lines));
    }

    public function insertBatch(TableSchemaData $table, array $columnNames, array $rows): string
    {
        if ($rows === []) {
            return '';
        }

        $columnIndex = [];
        foreach ($table->columns as $column) {
            $columnIndex[$column->name] = $column;
        }

        $quotedColumns = implode(', ', array_map(
            $this->quoteIdentifier(...),
            $columnNames,
        ));

        $tuples = [];
        foreach ($rows as $row) {
            $values = [];
            foreach ($columnNames as $col) {
                $column = $columnIndex[$col] ?? null;
                $values[] = $this->quoteValue($row[$col] ?? null, $column);
            }

            $tuples[] = '('.implode(', ', $values).')';
        }

        return sprintf(
            "%s %s (%s) VALUES\n%s;\n",
            $this->insertKeyword(),
            $this->qualifiedTable($table->name),
            $quotedColumns,
            implode(",\n", $tuples),
        );
    }

    protected function insertKeyword(): string
    {
        return 'INSERT INTO';
    }

    /** Quote a single value for a VALUES tuple based on the (optional) column metadata. */
    protected function quoteValue(mixed $value, ?ColumnSchemaData $column): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $this->booleanLiteral($value);
        }

        // Narrow the mixed PDO value to a string representation.
        if (is_int($value) || is_float($value)) {
            $str = (string) $value;
            $isNumeric = true;
        } elseif (is_string($value)) {
            $str = $value;
            $isNumeric = is_numeric($value);
        } else {
            $encoded = json_encode($value);
            $str = $encoded === false ? '' : $encoded;
            $isNumeric = false;
        }

        if ($column instanceof ColumnSchemaData && $this->isBinaryType($column->type)) {
            return $this->binaryLiteral(bin2hex($str));
        }

        if ($column instanceof ColumnSchemaData && $this->isBooleanType($column->type)) {
            $bool = filter_var($str, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);

            return $this->booleanLiteral($bool ?? ($str === '1'));
        }

        if ($column instanceof ColumnSchemaData && $this->isNumericType($column->type) && $isNumeric) {
            return $str;
        }

        return $this->stringLiteral($str);
    }

    /** Escape and quote a string literal. SQL Server overrides this with the `N'...'` form. */
    protected function stringLiteral(string $value): string
    {
        return "'".str_replace("'", "''", $value)."'";
    }

    protected function booleanLiteral(bool $value): string
    {
        return $value ? '1' : '0';
    }

    /**
     * Canonical base type token derived from the many DBMS spellings.
     * Returns one of: boolean, tinyint, smallint, int, bigint, float, double,
     * decimal, varchar, char, text, date, datetime, timestamp, time, json,
     * blob, uuid, enum, or the lowercased input when unknown.
     */
    protected function normalize(string $type): string
    {
        $t = strtolower(trim($type));

        return match (true) {
            in_array($t, ['bool', 'boolean', 'bit'], true) => 'boolean',
            $t === 'tinyint' => 'tinyint',
            in_array($t, ['smallint', 'int2'], true) => 'smallint',
            in_array($t, ['mediumint', 'int', 'integer', 'int4'], true) => 'int',
            in_array($t, ['bigint', 'int8'], true) => 'bigint',
            in_array($t, ['float', 'real', 'float4'], true) => 'float',
            in_array($t, ['double', 'double precision', 'float8'], true) => 'double',
            in_array($t, ['decimal', 'numeric', 'money', 'smallmoney'], true) => 'decimal',
            in_array($t, ['char', 'bpchar', 'nchar', 'character'], true) => 'char',
            in_array($t, ['varchar', 'nvarchar', 'character varying', 'varchar2', 'string'], true) => 'varchar',
            in_array($t, ['text', 'longtext', 'mediumtext', 'tinytext', 'ntext', 'clob'], true) => 'text',
            $t === 'date' => 'date',
            in_array($t, ['datetime', 'datetime2', 'smalldatetime'], true) => 'datetime',
            in_array($t, ['timestamp', 'timestamp without time zone', 'timestamp with time zone', 'timestamptz', 'datetimeoffset'], true) => 'timestamp',
            in_array($t, ['time', 'time without time zone'], true) => 'time',
            in_array($t, ['json', 'jsonb'], true) => 'json',
            in_array($t, ['blob', 'longblob', 'mediumblob', 'tinyblob', 'bytea', 'binary', 'varbinary', 'image'], true) => 'blob',
            in_array($t, ['uuid', 'uniqueidentifier'], true) => 'uuid',
            $t === 'enum' => 'enum',
            default => $t,
        };
    }

    protected function isBinaryType(string $type): bool
    {
        return $this->normalize($type) === 'blob';
    }

    protected function isBooleanType(string $type): bool
    {
        return $this->normalize($type) === 'boolean';
    }

    protected function isNumericType(string $type): bool
    {
        return in_array(
            $this->normalize($type),
            ['tinyint', 'smallint', 'int', 'bigint', 'float', 'double', 'decimal'],
            true,
        );
    }
}
