<?php

declare(strict_types=1);

use App\Data\Cloning\CloningOptionsData;
use App\Data\ConnectionData;
use App\Data\Schema\ColumnSchemaData;
use App\Data\Schema\DatabaseSchemaData;
use App\Data\Schema\TableSchemaData;
use App\Enums\DatabaseConnectionType;
use App\Services\SqlDump\DumpArchiver;
use App\Services\SqlDump\DumpDialectFactory;
use App\Services\SqlDump\SqlDumpService;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Storage;

function dumpConn(string $password = '', DatabaseConnectionType $dialect = DatabaseConnectionType::Mysql): ConnectionData
{
    return new ConnectionData(
        name: 'staging-dump', type: DatabaseConnectionType::Dump, host: null, port: null,
        database: null, schema: null, username: null, password: $password,
        isProduction: false, dialect: $dialect,
    );
}

function dumpSource(): ConnectionData
{
    return new ConnectionData(
        name: 'source', type: DatabaseConnectionType::Mysql, host: 'localhost', port: 3306,
        database: 'shop', schema: null, username: 'root', password: '', isProduction: false,
    );
}

function dumpSchema(): DatabaseSchemaData
{
    return new DatabaseSchemaData(databaseName: 'shop', tables: [
        new TableSchemaData('users', [
            new ColumnSchemaData('id', 'int', false, null, true),
            new ColumnSchemaData('email', 'varchar', false, null, false),
        ], []),
    ]);
}

function dumpOptions(): CloningOptionsData
{
    return new CloningOptionsData(
        chunkSize: 100, enforceColumnTypes: false, dropUnknownTables: false,
        dropExtraColumns: false, disableForeignKeyChecks: true, fakerLocale: 'en_US',
    );
}

function makeService(): SqlDumpService
{
    return new SqlDumpService(new DumpDialectFactory, new DumpArchiver);
}

it('writes header, preamble and DDL to the intermediate .sql file', function (): void {
    Storage::fake('local');
    $service = makeService();

    $service->begin(dumpConn(), dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));

    $sql = Storage::disk('local')->get($service->sqlFileName());

    expect($service->sqlFileName())->toBe('shop_20260524_123456.sql')
        ->and($sql)->toContain('-- Dump generated by Clonio for MySQL')
        ->and($sql)->toContain('-- Source: shop')
        ->and($sql)->toContain('SET FOREIGN_KEY_CHECKS = 0;')
        ->and($sql)->toContain('CREATE TABLE IF NOT EXISTS `users`');
});

it('appends INSERT batches and finalises into a ZIP, deleting the .sql', function (): void {
    Storage::fake('local');
    $service = makeService();

    $service->begin(dumpConn(), dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));
    $service->writeRows('users', [['id' => 1, 'email' => 'a@b.c'], ['id' => 2, 'email' => 'd@e.f']]);

    $sqlBefore = Storage::disk('local')->get($service->sqlFileName());
    expect($sqlBefore)->toContain('INSERT INTO `users` (`id`, `email`) VALUES')
        ->and($sqlBefore)->toContain("(1, 'a@b.c')");

    $result = $service->finish();

    expect(Storage::disk('local')->exists('shop_20260524_123456.sql'))->toBeFalse()
        ->and(Storage::disk('local')->exists('shop_20260524_123456.zip'))->toBeTrue()
        ->and($result->zipFileName)->toBe('shop_20260524_123456.zip')
        ->and($result->encrypted)->toBeFalse()
        ->and($result->sha256)->toMatch('/^[0-9a-f]{64}$/')
        ->and($result->zipBytes)->toBeGreaterThan(0);
});

it('produces an AES-256 encrypted archive when a password is set', function (): void {
    Storage::fake('local');
    $service = makeService();

    $service->begin(dumpConn('s3cret'), dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));
    $service->writeRows('users', [['id' => 1, 'email' => 'a@b.c']]);
    $result = $service->finish();

    expect($result->encrypted)->toBeTrue()
        ->and(Storage::disk('local')->exists($result->zipFileName))->toBeTrue();

    // Encrypted entry cannot be read without the password.
    $zip = new ZipArchive;
    $zip->open(Storage::disk('local')->path($result->zipFileName));
    expect($zip->getFromIndex(0))->toBeFalse();
    $zip->close();
});

it('omits FK preamble when disable_foreign_key_checks is false', function (): void {
    Storage::fake('local');
    $service = makeService();
    $options = new CloningOptionsData(100, false, false, false, false, 'en_US');

    $service->begin(dumpConn(), dumpSource(), dumpSchema(), ['users'], $options, new DateTimeImmutable('2026-05-24 12:34:56'));

    expect(Storage::disk('local')->get($service->sqlFileName()))->not->toContain('SET FOREIGN_KEY_CHECKS');
});

it('skips DDL but keeps the file when emitSchema is false', function (): void {
    Storage::fake('local');
    $service = makeService();

    $service->begin(dumpConn(), dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'), false);

    $sql = Storage::disk('local')->get($service->sqlFileName());
    expect($sql)->not->toContain('CREATE TABLE')
        ->and($sql)->toContain('SET FOREIGN_KEY_CHECKS = 0;');
});

it('derives the source name from a SQLite path without extension', function (): void {
    Storage::fake('local');
    $service = makeService();
    $sqliteSource = new ConnectionData('src', DatabaseConnectionType::Sqlite, null, null, '/tmp/prod.sqlite', null, null, '', false);

    $service->begin(dumpConn(), $sqliteSource, dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));

    expect($service->sqlFileName())->toBe('prod_20260524_123456.sql');
});

it('throws when the dialect is missing', function (): void {
    Storage::fake('local');
    $bad = new ConnectionData('d', DatabaseConnectionType::Dump, null, null, null, null, null, '', false, dialect: null);

    expect(fn () => makeService()->begin($bad, dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable))
        ->toThrow(RuntimeException::class);
});

it('throws when finish() is called before begin()', function (): void {
    Storage::fake('local');

    expect(fn () => makeService()->finish())->toThrow(RuntimeException::class, 'before begin');
});

it('writeRows is a no-op before begin() and for unknown tables', function (): void {
    Storage::fake('local');
    $service = makeService();

    // Before begin(): nothing to write, no error.
    $service->writeRows('users', [['id' => 1]]);

    $service->begin(dumpConn(), dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));
    $service->writeRows('does_not_exist', [['id' => 1]]);

    expect(Storage::disk('local')->get($service->sqlFileName()))->not->toContain('does_not_exist');
});

it('decrypts an encrypted ZIP password and produces an AES archive', function (): void {
    config(['app.key' => 'base64:ROzyPViGEkER6n3g0OHblde5CygEIcuDlAFbca99xvM=']);
    Storage::fake('local');
    $service = makeService();
    $conn = dumpConn('encrypted:'.Crypt::encryptString('topsecret'));

    $service->begin($conn, dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));
    $service->writeRows('users', [['id' => 1, 'email' => 'a@b.c']]);

    expect($service->finish()->encrypted)->toBeTrue();
});

it('throws when an encrypted ZIP password cannot be decrypted', function (): void {
    config(['app.key' => 'base64:ROzyPViGEkER6n3g0OHblde5CygEIcuDlAFbca99xvM=']);
    Storage::fake('local');
    $conn = dumpConn('encrypted:not-a-valid-payload');

    expect(fn () => makeService()->begin($conn, dumpSource(), dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable))
        ->toThrow(RuntimeException::class, 'decrypt');
});

it('falls back to "dump" when the source has no database name', function (): void {
    Storage::fake('local');
    $service = makeService();
    $noDb = new ConnectionData('s', DatabaseConnectionType::Mysql, 'localhost', 3306, null, null, 'root', '', false);

    $service->begin(dumpConn(), $noDb, dumpSchema(), ['users'], dumpOptions(), new DateTimeImmutable('2026-05-24 12:34:56'));

    expect($service->sqlFileName())->toBe('dump_20260524_123456.sql');
});
